config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

  # _post_nav 顯示異常修正：點選分類後按 sort_link，all 分類會變 active
  resources :categories, only: [:show]

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update] # 新增已用 posts#create 表單輸入處理
    member do
      post :collect
      post :uncollect
    end
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get :drafts
      get :comments
      get :collections
      get :friends
    end
  end

  resources :friendships, only: :create do
    member do
      post   :accept
      delete :ignore
    end
  end

  resources :feeds, only: :index

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  namespace :admin do
    root "categories#index"
    resources :categories
    resources :users, only: [:index, :update]
  end

end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :content

  belongs_to :user

  has_many :category_posts, dependent: :destroy # 關係刪除才能，分類空時才能刪除
  has_many :categories, through: :category_posts

  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, source: :user

  has_many :vieweds, dependent: :destroy
  has_many :viewed_users, through: :vieweds, source: :user

  has_many :collections, dependent: :destroy
  has_many :collected_users, through: :collections, source: :user

  mount_uploader :image, ImageUploader

  # 對單數
  def is_public?
    self.status == "public"
  end

  # 對複數 @category.posts 或 Post
  def self.are_public?
    Post.where(status: "public")
  end

  # Chaining Query Rails 5 按 all，friend，myself partition 依序 query
  def self.are_viewable?(user)
    Post.where(
      authority: "all").
    or(where(authority: "myself", user: user)#).
    # or(where(user: user)).                    # current_user all friends 是否包含 current_user 自己，待測
    # or(where(authority: "friend", user: user) # 朋友關係待新增
    )
  end

  # show 功能：文章權限判斷，已讀 user 數量計數
  # 文章權限判斷：對單數 @post
  def authority?(user)
    Post.are_viewable?(user).are_public?.include?(self)
  end
  # 已知 user 判斷 post 已讀？：@post.seen_by?(user)
  # 避免重覆計數
  def seen_by?(user)
    self.viewed_users.include?(user) #show 建立 @post.vieweds => counter_cache 計數器
  end

  def is_collected?(user)
    self.collected_users.include?(user)
  end

  def editable_post?(editor)
    self.user == editor || editor.admin?
  end

end

app/views/shared/_admin_navtab.html.erb
<div class="container">
  <div class="row">
    <div class="navtab">
      <ul class="nav nav-tabs">
        <li role="presentation" class="<%= 'active' if current_page?(admin_categories_path) %>">
          <%= link_to "Category List", admin_categories_path %>
        </li>
        <li role="presentation" class="<%= 'active' if current_page?(admin_users_path) %>">
          <%= link_to "User List", admin_users_path %>
        </li>
      </ul>
    </div>
    <br/>
  </div>
</div>

app/views/shared/_collect_button.html.erb
<% if post.is_collected?(current_user) %>
  <%= link_to "Uncollect", uncollect_post_path(post), remote: true, method: :post, class: "btn btn-sm btn-default", id: "uncollect-#{post.id}" %>
<% else %>
  <%= link_to "Collect", collect_post_path(post), remote: true, method: :post, class: "btn btn-sm btn-primary", id: "collect-#{post.id}" %>
<% end %>

app/views/shared/_comment_edit_button.html.erb
<% if comment.editable_comment?(current_user) %>
  <div class="comment_buttons">
    <%= link_to edit_post_comment_path(post, comment) do %>
      <i class="fa fa-pencil" aria-hidden="true"></i>
    <% end %>
    <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure？" } do %>
      <i class="fa fa-trash-o"  aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_comment_info.html.erb
<div class="comment_content<%= ' margin_for_btn' if comment.editable_comment?(current_user) %>"><%= comment.content %></div><!-- 注意：margin_for_btn 前有空一格 -->
<div class="float_right_bottom">
  <%= render partial: "shared/comment_edit_button", locals: { post: @post, comment: comment } %>
</div>

app/views/shared/_edit_buttons.html.erb
<% if post.user == current_user || current_user.admin? %>
  <div class="buttons">
    <%= link_to edit_post_path(post) do %>
      <i class="fa fa-edit fa-2x"></i>
    <% end %>
    <%= link_to post_path(post), method: :delete, data: { confirm: "Are you sure？" } do %>
      <i class="fa fa-trash fa-2x"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_friend_button.html.erb
<% if user !=  current_user %><!-- 若變數使用者非當前使用者，則… -->
  <% unless current_user.friend?(user) %><!-- 若變數使用者 不屬於 當前使用者真朋友群，則…(分割) -->
    <% if current_user.inverse_request_friend?(user) %><!-- 若變數使用者 屬於 當前使用者的反向邀請者 -->
      <%= link_to "Accept", accept_friendship_path(user), class: "btn btn-primary", method: :post %><br>
      <%= link_to "Ignore", ignore_friendship_path(user), class: "btn btn-danger", method: :delete %>
    <% elsif current_user.request_friend?(user) %><!-- 若變數使用者 屬於 當前使用者的邀請者，無顯示按鈕需求 -->
    <% else %><!-- 非朋友 -->
      <%= link_to "Friend", friendships_path(friend_id: user), class: "btn btn-primary", method: :post %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_navtab.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-tabs">
        <li role="presentation"<%= 'class=active' if current_page?(user_path) %>><!-- 注意 class=active 括號位置 -->
          <!-- 注意 active 屬性掛在 lint_to 後面無效 -->
          <%= link_to "My Post", user_path(user), class: "nav-link bg-light" %>
        </li>
        <li role="presentation"<%= 'class=active' if current_page?(comments_user_path) %>>
          <%= link_to "My Comment", comments_user_path(user), class: "nav-link bg-light" %>
        </li>
        <li role="presentation"<%= 'class=active' if current_page?(collections_user_path) %>>
          <%= link_to "My Collect", collections_user_path(user), class: "nav-link bg-light" %>
        </li>
        <li role="presentation"<%= 'class=active' if current_page?(drafts_user_path) %>>
          <%= link_to "My Draft", drafts_user_path(user), class: "nav-link bg-light" %>
        </li>
        <li role="presentation"<%= 'class=active' if current_page?(friends_user_path) %>>
          <%= link_to "My Friend", friends_user_path(user), class: "nav-link bg-light" %>
        </li>
      </ul>
    </div>
  </div>
</div>
<br/>

app/views/shared/_post.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 mt-4">
      <%= form_for @post do |f| %>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Title", class: "form-control bg-light" %>
        </div>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control bg-light", rows:"10" %>
        </div>

        <!-- Upload_button -->
        <label class="btn btn-default upload_button">
          File
          <spna style="display: none"><!-- 不顯示預設，再外包樣式 -->
            <%= f.file_field :image %>
          </spna>
        </label>

        <!-- Radio-button table -->
        <table class="new_table">
          <tr>
            <td>
              <div class="new_title">
                Who Can See
              </div>
            </td>
            <td class="new_td">
              <span class="input"><!-- span 水平排列 -->
                <%= radio_button :post, :authority, "all", { checked: true } %>
                <%= label_tag :All, "All" %>
              </span>
            </td>
            <td class="new_td">
              <span class="input">
                <%= radio_button :post, :authority, "friend" %>
                <%= label_tag :Friend, "Friend" %>
              </span>
            </td>
            <td class="new_td">
              <span class="input">
                <%= radio_button :post, :authority, "myself" %>
                <%= label_tag :Myself, "Myself" %>
              </span>
            </td>
          </tr>
        </table>

        <!-- checkbox-button table -->
        <table class="new_table">
          <tr>
            <td>
              <div class="new_title">
                Category
              </div>
            </td>

            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, {}, {multiple: true, class: "form-check-input"} do |c| %>
              <td class="new_td">
                <span class="form-check">
                  <%= c.label(class: "form-check-label") { c.check_box(class: "form-check-input") + c.text } %>
                </span>
              </td>
            <% end %>
          </tr>
        </table>

        <div class="new_title">
          Status: <%= @post.status %>
        </div>
        <br />

        <!-- multi submit -->
        <div class="form-group">
          <%= f.submit "Save Draft", name: "draft", class: "btn btn-default" %>
          <%= f.submit "Submit", name: "public", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_post_edit_button.html.erb
<% if @post.editable_post?(current_user) %>
  <div class="post_buttons">
    <%= link_to edit_post_path(@post) do %>
      <i class="fa fa-pencil" aria-hidden="true"></i>
    <% end %>
    <%= link_to post_path(@post), method: :delete, data: { confirm: "Are you sure？" } do %>
      <i class="fa fa-trash-o"  aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_post_info.html.erb
<div class="image"><%= image_tag @post.image, style: "width: 100%;" if @post.image? %></div>
<div class="post_content<%= ' margin_for_btn' if @post.editable_post?(current_user) %>"><%= @post.content %></div><!-- 注意：margin_for_btn 前有空一格 -->
<div class="float_right_bottom">
  <%= render partial: "shared/post_edit_button", locals: { user: user } %>
</div>

app/views/shared/_post_user_info.html.erb
<div><%= image_tag user.avatar, width: 140, height: 140 if user.avatar? %></div>
<div class="avatar_name"><%= user.name %></div>
<div class="friend_button" id="user-<%= user.id %>"><!-- Ajax prepare -->
  <%= render partial: "shared/friend_button", locals: { user: user } %>
</div>

app/views/shared/_user_info.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="user_profile col-md-12">

      <section class="text-center col-md-2"><!-- avatar -->
        <%= link_to user_path(user) do %>
          <%= image_tag user.avatar, width: 140, height: 140 if user.avatar? %>
          <div class="avatar_name"><%= user.name %></div>
        <% end %>
      </section>
      <section class="profile_right col-md-10 clearfix">
        <div class="content<%= ' margin_for_user_btn' if user_button?(user) %>"><%= user.intro %></div>

        <div class="float_r_b">
          <% if user == current_user %>
            <div class="user_button">
              <%= link_to "Edit", edit_user_path(user), class: "btn btn-default" %>
            </div>
          <% elsif !current_user.inverse_request_friend?(user) %><!-- 加顯示條件：阻檔 inverse_request 顯示 -->
            <div class="friend_button" id="user-<%= user.id %>"><!-- 此處pull-right強過 CSS 置中設定 -->
              <%= render partial: "shared/friend_button", locals: { user: user } %>
            </div>
          <% end %>
        </div>
      </section>

    </div>
  </div>
</div>

app/views/shared/_user_item.html.erb
<div class="text-center">
  <%= link_to user_path(user) do %>
    <%= image_tag user.avatar, width: 80, height: 80 if user.avatar? %>
    <div class="avatar_name"><%= user.name %></div>
  <% end %>
</div>
<div class="friend_button" id="user-<%= user.id %>"><!-- Ajax prepare -->
  <%= render partial: "shared/friend_button", locals: { user: user } %>
</div>