config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

  # _post_nav 顯示異常修正：點選分類後按 sort_link，all 分類會變 active
  resources :categories, only: [:show]

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update] # 新增已用 posts#create 表單輸入處理
    member do
      post :collect
      post :uncollect
    end
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get :drafts
      get :comments
      get :collections
      get :friends
    end
  end

  resources :friendships, only: :create do
    member do
      post   :accept
      delete :ignore
    end
  end

  resources :feeds, only: :index

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  namespace :admin do
    root "categories#index"
    resources :categories
    resources :users, only: [:index, :update]
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :category_posts, dependent: :restrict_with_error
  has_many :posts, through: :category_posts

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]

  def index
    @categories = Category.all
    if params[:id]
      @category = Category.find(params[:id])
    else
      @category = Category.new
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category was successfully updated!"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def destroy
    if @category.destroy
      flash[:notice] = "Category was successfully deleted!"
      redirect_to admin_categories_path
    else
      flash[:alert] = @category.errors.full_messages.to_sentence
      redirect_to admin_categories_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # _post_nav 顯示異常修正：點選分類後按 sort_link，all 分類會變 active
  # template 同 posts#index
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @q = @category.posts.are_public?.where(authority: "all").or(@category.posts.are_viewable?(current_user).are_public?).ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:comments).page(params[:page]).per(20)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<%= render partial: "shared/admin_navtab" %>
<div class="container">
  <div class="row">
    <%= form_for [:admin, @category], html: { class: "form-inline mb-3" } do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "Category Name", class: "form-control" %>
      </div>
      <%= f.submit class: "btn btn-primary" %>
      <% if @category.errors.any? %>
        <%= @category.errors.full_messages.to_sentence %>
      <% end %>
    <% end %>
    <br />
    <table class="table table-hover table-bordered">
      <thead class="table_title">
        <tr>
          <th>Name</th>
          <th>#</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td>
              <div class="title_button">
                <%= link_to "Edit", admin_categories_path(id: category.id), class: "btn btn-primary" %>
                <%= link_to "Delete", admin_category_path(category), method: :delete, data: { confirm: "Are you sure??" }, class: "btn btn-default" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>