config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

  # _post_nav 顯示異常修正：點選分類後按 sort_link，all 分類會變 active
  resources :categories, only: [:show]

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update] # 新增已用 posts#create 表單輸入處理
    member do
      post :collect
      post :uncollect
    end
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get :drafts
      get :comments
      get :collections
      get :friends
    end
  end

  resources :friendships, only: :create do
    member do
      post   :accept
      delete :ignore
    end
  end

  resources :feeds, only: :index

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  namespace :admin do
    root "categories#index"
    resources :categories
    resources :users, only: [:index, :update]
  end

end

app/views/layouts/_alert.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-success alert-dismissible text-center" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><p aria-hidden="true">&times;</p></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-dismissible text-center" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>
</div>
<br>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="container">
    <nav>
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag("logo.png") %><!-- app/assets/images/logo.png -->
        <% end %>
      </div>

      <!-- menu -->
      <div class="navbar" id="myNavbar">
        <ul>
          <li><%= link_to "Feeds", feeds_path %></li>
          <li><%= link_to "All Post", root_path %></li>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><!-- 管理者登入顯示後台連結 -->
            <% if current_user && current_user.admin? %>
              <%= link_to admin_categories_path do %>
                <%= "Back-End" %> <i class="fa fa-users"></i>
              <% end %>
            <% end %>              
          </li>
          <li class="icon" onclick="navBarToogle()"><a href="javascript:void(0);" >&#9776;</a></li>
        </ul>
      </div>

      <!-- 頭像連結個人頁面 profile -->
      <div id="profile">
        <% if current_user %>
          <%= link_to user_path(current_user) do %>
            <%= image_tag current_user.avatar, height: 50, width: 50 if current_user.avatar? %>
          <% end %>
        <% end %>
      </div>

      <!-- devise logout -->
      <ul class="nav-right">
        <li>
          <% if current_user %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= "Logout" %> <i class="fa fa-sign-out"></i>
            <% end %>
          <% else %>
            <%= link_to 'Change Password', edit_user_registration_path %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div><!-- container end -->
  <!-- token -->
  <%# if current_user %>
    <%# current_user.authentication_token  %>
  <%# end %>
</header>

<div class="nav_margin"></div><!-- div collapse -->

<script>
  function navBarToogle() {
    var x = document.getElementById("myNavbar");
    if (x.className === "navbar") {
      // 注意要空一格，否則會連在一起就失效了
      x.className += " " + "responsive";
    } else {
      x.className = "navbar";
    }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> <!-- google font -->
    <%= yield :header %>
  </head>

  <body>
    <%= render partial: '/layouts/header' %>
    <%= render partial: '/layouts/alert' %>
    <%= yield %>
  </body>
</html>